version: '3.8'
services:
  course:
    image: ghcr.io/nervus-tech/nervus-course:v1.0.0
    ports:
      - "8093:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/nervus
      - SPRING_DATASOURCE_USERNAME=nervus_user
      - SPRING_DATASOURCE_PASSWORD=secure_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=course
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=minio_access
      - MINIO_SECRET_KEY=minio_secret
    depends_on:
      - postgres
      - minio
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=nervus
      - POSTGRES_USER=nervus_user
      - POSTGRES_PASSWORD=secure_password
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio_access
      - MINIO_ROOT_PASSWORD=minio_secret
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
volumes:
  pgdata:
  minio_data: 