version: '3.8'
services:
  course-staging:
    image: ghcr.io/nervus-tech/nervus-course:v1.1.0-staging
    container_name: course-staging
    ports:
      - "8094:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/nervus
      - SPRING_DATASOURCE_USERNAME=nervus_user
      - SPRING_DATASOURCE_PASSWORD=secure_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - HIBERNATE_DEFAULT_SCHEMA=staging_course
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=minio_access
      - MINIO_SECRET_KEY=minio_secret
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka:8761/eureka/
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
    networks:
      - nervus-infrastructure_default
    # depends_on removed - expects shared infrastructure Postgres
  # Postgres service removed - expects shared infrastructure

networks:
  nervus-infrastructure_default:
    external: true 